### ISSUE TITLE
Arm64 support

### ISSUE THREAD

**Issue by junior** [godror/godror#155]
**Is your feature request related to a problem? Please describe.**
Trying to build for Arm64/aarch64 generates an undefined error. Oracle Instant Client supports Arm64 for some time now and the whole market is going to this path, either on the Cloud(linux/arm64) or on the Client (Apple's M1, Raspberry PIs, and others). Right now, just Java allow that, and people would prefer to change the DB instead to change from Go to Java.

**Describe the solution you'd like**
godror support for Arm64 platforms

**Describe alternatives you've considered**
No alternatives. when trying to build on arm64 platform the errors are always the same:

```shell
#25 37.07 # github.com/godror/godror
#25 37.07 /go/pkg/mod/github.com/godror/godror@v0.24.7/orahlp.go:478:56: undefined: VersionInfo
#25 37.07 /go/pkg/mod/github.com/godror/godror@v0.24.7/orahlp.go:487:56: undefined: VersionInfo
#25 37.07 /go/pkg/mod/github.com/godror/godror@v0.24.7/orahlp.go:505:19: undefined: VersionInfo
#25 37.07 /go/pkg/mod/github.com/godror/godror@v0.24.7/orahlp.go:506:19: undefined: VersionInfo
#25 37.07 /go/pkg/mod/github.com/godror/godror@v0.24.7/orahlp.go:507:31: undefined: ObjectType
#25 37.07 /go/pkg/mod/github.com/godror/godror@v0.24.7/orahlp.go:508:31: undefined: Event
#25 37.07 /go/pkg/mod/github.com/godror/godror@v0.24.7/orahlp.go:508:42: undefined: SubscriptionOption
#25 37.07 /go/pkg/mod/github.com/godror/godror@v0.24.7/orahlp.go:508:64: undefined: Subscription
#25 37.07 /go/pkg/mod/github.com/godror/godror@v0.24.7/orahlp.go:509:10: undefined: StartupMode
#25 37.07 /go/pkg/mod/github.com/godror/godror@v0.24.7/orahlp.go:510:11: undefined: ShutdownMode
#25 37.07 /go/pkg/mod/github.com/godror/godror@v0.24.7/orahlp.go:510:11: too many errors
#25 ...
```

Note that this example is using a code that build without problems when using GOARCH=amd64 and GOOS=linux. The problem only happen when change to GOARCH=arm64.

**Comment by junior** [comment]
Tests done using:

Go: **1.16**
Instant Client: **19.10**   Ref: http://yum.oracle.com/repo/OracleLinux/OL8/oracle/instantclient/aarch64/index.html
GOOS: **Linux**
GOARCH: **Arm64**

**Comment by cjbj** [comment]
> Arm64 for some time now

10 days :)

**Comment by junior** [comment]
> > Oracle Instant Client supports Arm64 for some time now
> 
> 10 days :)

Had to make more dramatic 😄. Arm64 is there for a long time and consolidated. Hope godror is considering to support on their short plans. 😉

**Comment by tgulacsi** [comment]
@junior are you trying to [cross-compile](https://github.com/godror/godror/blob/master/doc/cross-compile.md) ?
Then you'll need the cross-compiling C compilers.

**Comment by junior** [comment]
@tgulacsi I've used cross-compile using build with go 1.16.  xgo mentioned on the [cross-compile](https://github.com/godror/godror/blob/master/doc/cross-compile.md) appear to be stopped on go 1.13...
...but...
I've tried the xgo and was able to compile my project. Now I need to simplify the process and build in a Github Action and test that everything is working. I'll post here the results.

Many Thanks for the heads up.

**Comment by junior** [comment]
Just to clarify, worked for linux/arm64. Appears that ignores Darwin/arm64 (xgo probably need to be updated to go 1.160

**Comment by junior** [comment]
Maybe the use of xgo is overkill and not necessary. Some people even fixed the issue with the Go version support supporting 1.16.x [here](https://github.com/techknowlogick/xgo).

But you really do not need it. After some tests, the most practical choice was using Buildkit and simplify selecting the platforms that I want to build.

**Comment by junior** [comment]
Cross compile example using docker's buildx. Simpler and easier. https://github.com/oracle-quickstart/oci-cloudnative/blob/5aab22041bf1c19da2599ba6402f0776df6cb7f6/deploy/basic/Dockerfile#L99,L157

**Comment by machship-mm** [comment]
@junior were you able to get oracle instant client working on an M1 Mac?

**Comment by junior** [comment]
> @junior were you able to get oracle instant client working on an M1 Mac?

Only using docker installing the Linux aarch64 version of the Oracle Instant Client. Don't think the team have included darwin-arm64 platform yet for native install.

**Comment by ankurnigam** [comment]
Did we get solution for this as I am also facing the same issue when building for arm64.

**Comment by ankurnigam** [comment]
# github.com/godror/godror
vendor/github.com/godror/godror/orahlp.go:505:19: undefined: VersionInfo
vendor/github.com/godror/godror/orahlp.go:506:19: undefined: VersionInfo
vendor/github.com/godror/godror/orahlp.go:507:31: undefined: ObjectType
vendor/github.com/godror/godror/orahlp.go:508:31: undefined: Event
vendor/github.com/godror/godror/orahlp.go:508:42: undefined: SubscriptionOption
vendor/github.com/godror/godror/orahlp.go:508:64: undefined: Subscription
vendor/github.com/godror/godror/orahlp.go:509:10: undefined: StartupMode
vendor/github.com/godror/godror/orahlp.go:510:11: undefined: ShutdownMode
vendor/github.com/godror/godror/orahlp.go:511:59: undefined: Data
vendor/github.com/godror/godror/orahlp.go:514:18: undefined: PoolStats
vendor/github.com/godror/godror/orahlp.go:514:18: too many errors

**Comment by tgulacsi** [comment]
The answer is still the same: cross-compilation needs C cross-compiler.

**Comment by junior** [comment]
> Did we get solution for this as I am also facing the same issue when building for arm64.

The best option that I found was using Docker. Can be as simple as including both platforms on the same docker creating both Binaries or better, create a multi-arch docker image.

Both Binaries:
https://github.com/oracle-quickstart/oci-cloudnative/blob/085b379a7df68b046ba6444cb51d8b6535f24dd9/deploy/basic/Dockerfile#L99-L157

Multi-arch:
https://github.com/oracle-quickstart/oci-cloudnative/blob/master/src/catalogue/Dockerfile

You can easily point the binary to generate locally using volumes.

Here a Github action that builds and push the images for you: https://github.com/oracle-quickstart/oci-cloudnative/blob/master/.github/workflows/containers.yml
